In [26]:
import numpy as np 

def create_matrix(mc):
    print("\nARRAY "+str(mc)+" Elements : ")
    array_1 = map(int, input().split())
    array_1 = np.array(list(array_1))
    
    print("\nARRAY "+str(mc)+" ,  ROW COLUMN : ")
    row,column = map(int, input().split())
    if(len(array_1)!= (row*column)):
        print("\nRow and Column size not match with total elements !! retry")
        return create_matrix(mc)
    array_1 = array_1.reshape(row,column)
    print("\nARRAY "+str(mc))
    print(array_1)
    return array_1


arr1 = create_matrix(1)
arr2 = create_matrix(2)

if(arr1.shape == arr2.shape):
    print("\nDot product")
    print(np.dot(arr1,arr2))
else:
    print("\nDimensions not matching!")


ARRAY 1 Elements : 
5 4 8 9

ARRAY 1 ,  ROW COLUMN : 
2 2

ARRAY 1
[[5 4]
 [8 9]]

ARRAY 2 Elements : 
2 5 7 9

ARRAY 2 ,  ROW COLUMN : 
2 2

ARRAY 2
[[2 5]
 [7 9]]

Dot product
[[ 38  61]
 [ 79 121]]


In [28]:
import numpy as np 

def create_matrix(mc):
    print("\nARRAY "+str(mc)+" Elements : ")
    array_1 = map(int, input().split())
    array_1 = np.array(list(array_1))
    #print(arr)
    print("\nARRAY "+str(mc)+" ,  ROW COLUMN : ")
    row,column = map(int, input().split())
    if(len(array_1)!= (row*column)):
        print("\nRow and Column size not match with total elements !! retry")
        return create_matrix(mc)
    array_1 = array_1.reshape(row,column)
    print("\nARRAY "+str(mc))
    print(array_1)
    print("\nTranspose : ")
    return array_1



print(create_matrix(1).transpose())


ARRAY 1 Elements : 
1 2 3 4

ARRAY 1 ,  ROW COLUMN : 
2 2

ARRAY 1
[[1 2]
 [3 4]]

Transpose : 
[[1 3]
 [2 4]]


In [29]:
import numpy as np 

def create_matrix(mc):
    print("\nARRAY "+str(mc)+" Elements : ")
    array_1 = map(int, input().split())
    array_1 = np.array(list(array_1))
    #print(arr)
    print("\nARRAY "+str(mc)+" ,  ROW COLUMN : ")
    row,column = map(int, input().split())
    if(len(array_1)!= (row*column)):
        print("\nRow and Column size not match with total elements !! retry")
        return create_matrix(mc)
    array_1 = array_1.reshape(row,column)
    print("\nARRAY "+str(mc))
    print(array_1)
    print("\nTrase : ")
    return array_1



print(create_matrix(1).trace())


ARRAY 1 Elements : 
1 2 3 4

ARRAY 1 ,  ROW COLUMN : 
2 2

ARRAY 1
[[1 2]
 [3 4]]

Trase : 
5


In [30]:
import numpy as np 

def create_matrix(mc):
    print("\nARRAY "+str(mc)+" Elements : ")
    array_1 = map(int, input().split())
    array_1 = np.array(list(array_1))
    #print(arr)
    print("\nARRAY "+str(mc)+" ,  ROW COLUMN : ")
    row,column = map(int, input().split())
    if(len(array_1)!= (row*column)):
        print("\nRow and Column size not match with total elements !! retry")
        return create_matrix(mc)
    array_1 = array_1.reshape(row,column)
    print("\nARRAY "+str(mc))
    print(array_1)
    print("\nRank : ")
    return array_1



print(np.linalg.matrix_rank(create_matrix(1)))


ARRAY 1 Elements : 
1 2 3 4

ARRAY 1 ,  ROW COLUMN : 
2 2

ARRAY 1
[[1 2]
 [3 4]]

Rank : 
2


In [31]:
import numpy as np 

def create_matrix(mc):
    print("\nARRAY "+str(mc)+" Elements : ")
    array_1 = map(int, input().split())
    array_1 = np.array(list(array_1))
    #print(arr)
    print("\nARRAY "+str(mc)+" ,  ROW COLUMN : ")
    row,column = map(int, input().split())
    if(len(array_1)!= (row*column)):
        print("\nRow and Column size not match with total elements !! retry")
        return create_matrix(mc)
    array_1 = array_1.reshape(row,column)
    print("\nARRAY "+str(mc))
    print(array_1)
    print("\nDeterminant : ")
    return array_1



print(np.linalg.det(create_matrix(1)))


ARRAY 1 Elements : 
1 2 3 4

ARRAY 1 ,  ROW COLUMN : 
2 2 

ARRAY 1
[[1 2]
 [3 4]]

Determinant : 
-2.0000000000000004


In [32]:
import numpy as np 

def create_matrix(mc):
    print("\nARRAY "+str(mc)+" Elements : ")
    array_1 = map(int, input().split())
    array_1 = np.array(list(array_1))
    #print(arr)
    print("\nARRAY "+str(mc)+" ,  ROW COLUMN : ")
    row,column = map(int, input().split())
    if(len(array_1)!= (row*column)):
        print("\nRow and Column size not match with total elements !! retry")
        return create_matrix(mc)
    array_1 = array_1.reshape(row,column)
    print("\nARRAY "+str(mc))
    print(array_1)
    print("\nInverse : ")
    return array_1



print(np.linalg.inv(create_matrix(1)))


ARRAY 1 Elements : 
1 2 3 4

ARRAY 1 ,  ROW COLUMN : 
2 2

ARRAY 1
[[1 2]
 [3 4]]

Inverse : 
[[-2.   1. ]
 [ 1.5 -0.5]]


In [33]:
import numpy as np 

def create_matrix(mc):
    print("\nARRAY "+str(mc)+" Elements : ")
    array_1 = map(int, input().split())
    array_1 = np.array(list(array_1))
    #print(arr)
    print("\nARRAY "+str(mc)+" ,  ROW COLUMN : ")
    row,column = map(int, input().split())
    if(len(array_1)!= (row*column)):
        print("\nRow and Column size not match with total elements !! retry")
        return create_matrix(mc)
    array_1 = array_1.reshape(row,column)
    print("\nARRAY "+str(mc))
    print(array_1)
    return array_1



x,y = np.linalg.eig(create_matrix(1))

print("\nE-value : ")
print(x)
print("\nE-vector : ")
print(y)


ARRAY 1 Elements : 
1 2 3 4

ARRAY 1 ,  ROW COLUMN : 
2 2

ARRAY 1
[[1 2]
 [3 4]]

E-value : 
[-0.37228132  5.37228132]

E-vector : 
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
